### ISSUE TITLE
[Bug]:Out of memory error even when there is plenty memory available

### ISSUE THREAD

**Issue by FreSingh** [ciderapp/Fujisan-BugTracker#85] opened 2023-03-12 17:21 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11

### Describe the Bug

after a minute of starting up, the application spawns up an out of error page (similar to what it looks like on edge) even when there is about 58% memory unused 

### Steps to Reproduce

wait for a minute after launch of application

**Comment by coredev-uk** [comment] 2023-03-13 16:14
We're aware of this issue.

**Comment by coredev-uk** [comment] 2023-03-13 16:27
Duplicate of #65. Please check the issue list before making an issue.

**Closed by coredev-uk** 2023-03-13 16:27 UTC
Labels: 🐛 Bug, 🚀 ClientDB
